### PR TITLE
Re-format configuration files

### PR DESCRIPTION
**Pull request by yiannist**
Add detailed comments in the configuration files describing each and every field. The description should be consistent with the docs/admin-guide.rst.

### CODE REVIEW

**Comment by cnanakos** [comment]
lgtm

**Comment by louridas** [comment]
Merge it then :+1:

**Comment by yiannist** [comment]
The last commit was suggested by @philipgian . Also, I think we should add the suggested formula for the calculating the xseg SEGMENT_SIZE. Should I push another commit?

**Comment by philipgian** [comment]
Actually, currently archipelago start/stop script perform checks against that requirement.

**Pull request merged**
